# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mew's Secret Base
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  No one can understand the idea of kittens
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keith0506.github.io"
header-img: img/kitten.jpg

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Build settings
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
#featured-condition-size: 3              # A tag will be featured if the size of it is more than this condition value

# SNS settings
RSS: false
github_username: keith0506
